name: Publish Image to Dockerhub

#0 0 represents the minute and hour (midnight).
#1 represents the day of the month (first day of the month).
#1,4,7,10 represents the months (January, April, July, October).
on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io #ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      -
        name: create a custom version using run number
        run: |
            echo "VERSION_NUMBER_CUSTOM=$((1+GITHUB_RUN_NUMBER))" >> $GITHUB_ENV
      -
        name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-java-app:${{ env.VERSION_NUMBER_CUSTOM }}
          # TODO: tags: ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:simple-java-app-$SOME_BUILD_NUM